import 'package:chrom_ext/util/Converter.dart';

import 'Tree.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Recent {
/*
{
  "dateAdded": 1632213327647,
  "id": "54",
  "index": 26,
  "parentId": "19",
  "title": "android - Access argument data in Kotlin from Flutter's Method channel - Stack Overflow",
  "url": "https://stackoverflow.com/questions/59016157/access-argument-data-in-kotlin-from-flutters-method-channel"
}
*/

  int? dateAdded;
  String? id;
  int? index;
  String? parentId;
  String? title;
  String? url;

  static Recent fromJsons(Map<String, dynamic> json) =>
      Recent.fromJson(json);

  Recent({
    this.dateAdded,
    this.id,
    this.index,
    this.parentId,
    this.title,
    this.url,
  });

  Recent.fromJson(Map<String, dynamic> json) {
    dateAdded = json["dateAdded"]?.toInt();
    id = json["id"]?.toString();
    index = json["index"]?.toInt();
    parentId = json["parentId"]?.toString();
    title = json["title"]?.toString();
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["dateAdded"] = dateAdded;
    data["id"] = id;
    data["index"] = index;
    data["parentId"] = parentId;
    data["title"] = title;
    data["url"] = url;
    return data;
  }
}
