import 'package:chrom_ext/chrome.dart';
import 'package:chrom_ext/model/Recent.dart' as d;


///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TreeChildrenChildrenChildren {
/*
{
  "dateAdded": 1545833575704,
  "id": "6",
  "index": 0,
  "parentId": "5",
  "title": "ASUS Homepage",
  "url": "http://www.asus.com/"
} 
*/

  int? dateAdded;
  String? id;
  int? index;
  String? parentId;
  String? title;
  String? url;

  TreeChildrenChildrenChildren({
    this.dateAdded,
    this.id,
    this.index,
    this.parentId,
    this.title,
    this.url,
  });

  TreeChildrenChildrenChildren.fromJson(Map<String, dynamic> json) {
    dateAdded = json["dateAdded"]?.toInt();
    id = json["id"]?.toString();
    index = json["index"]?.toInt();
    parentId = json["parentId"]?.toString();
    title = json["title"]?.toString();
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["dateAdded"] = dateAdded;
    data["id"] = id;
    data["index"] = index;
    data["parentId"] = parentId;
    data["title"] = title;
    data["url"] = url;
    return data;
  }
}

class TreeChildrenChildren {
/*
{
  "children": [
    {
      "dateAdded": 1545833575704,
      "id": "6",
      "index": 0,
      "parentId": "5",
      "title": "ASUS Homepage",
      "url": "http://www.asus.com/"
    }
  ],
  "dateAdded": 1606119685398,
  "id": "5",
  "index": 0,
  "parentId": "1",
  "title": "ASUS E-Service"
} 
*/

  List<TreeChildrenChildrenChildren?>? children;
  int? dateAdded;
  String? id;
  int? index;
  String? parentId;
  String? title;

  TreeChildrenChildren({
    this.children,
    this.dateAdded,
    this.id,
    this.index,
    this.parentId,
    this.title,
  });

  TreeChildrenChildren.fromJson(Map<String, dynamic> json) {
    if (json["children"] != null) {
      final v = json["children"];
      final arr0 = <TreeChildrenChildrenChildren>[];
      v.forEach((v) {
        arr0.add(TreeChildrenChildrenChildren.fromJson(v));
      });
      children = arr0;
    }
    dateAdded = json["dateAdded"]?.toInt();
    id = json["id"]?.toString();
    index = json["index"]?.toInt();
    parentId = json["parentId"]?.toString();
    title = json["title"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (children != null) {
      final v = children;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["children"] = arr0;
    }
    data["dateAdded"] = dateAdded;
    data["id"] = id;
    data["index"] = index;
    data["parentId"] = parentId;
    data["title"] = title;
    return data;
  }
}

class TreeChildren {
/*
{
  "children": [
    {
      "children": [
        {
          "dateAdded": 1545833575704,
          "id": "6",
          "index": 0,
          "parentId": "5",
          "title": "ASUS Homepage",
          "url": "http://www.asus.com/"
        }
      ],
      "dateAdded": 1606119685398,
      "id": "5",
      "index": 0,
      "parentId": "1",
      "title": "ASUS E-Service"
    }
  ],
  "dateAdded": 1606119677055,
  "dateGroupModified": 1622352516105,
  "id": "1",
  "index": 0,
  "parentId": "0",
  "title": "Favorites bar"
} 
*/

  List<TreeChildrenChildren?>? children;
  int? dateAdded;
  int? dateGroupModified;
  String? id;
  int? index;
  String? parentId;
  String? title;

  TreeChildren({
    this.children,
    this.dateAdded,
    this.dateGroupModified,
    this.id,
    this.index,
    this.parentId,
    this.title,
  });

  TreeChildren.fromJson(Map<String, dynamic> json) {
    if (json["children"] != null) {
      final v = json["children"];
      final arr0 = <TreeChildrenChildren>[];
      v.forEach((v) {
        arr0.add(TreeChildrenChildren.fromJson(v));
      });
      children = arr0;
    }
    dateAdded = json["dateAdded"]?.toInt();
    dateGroupModified = json["dateGroupModified"]?.toInt();
    id = json["id"]?.toString();
    index = json["index"]?.toInt();
    parentId = json["parentId"]?.toString();
    title = json["title"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (children != null) {
      final v = children;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["children"] = arr0;
    }
    data["dateAdded"] = dateAdded;
    data["dateGroupModified"] = dateGroupModified;
    data["id"] = id;
    data["index"] = index;
    data["parentId"] = parentId;
    data["title"] = title;
    return data;
  }
}

class Tree extends d.Recent {
/*
{
  "children": [
    {
      "children": [
        {
          "children": [
            {
              "dateAdded": 1545833575704,
              "id": "6",
              "index": 0,
              "parentId": "5",
              "title": "ASUS Homepage",
              "url": "http://www.asus.com/"
            }
          ],
          "dateAdded": 1606119685398,
          "id": "5",
          "index": 0,
          "parentId": "1",
          "title": "ASUS E-Service"
        }
      ],
      "dateAdded": 1606119677055,
      "dateGroupModified": 1622352516105,
      "id": "1",
      "index": 0,
      "parentId": "0",
      "title": "Favorites bar"
    }
  ],
  "dateAdded": 1633360019842,
  "id": "0",
  "title": ""
} 
*/

  List<TreeChildren?>? children;
  int? dateAdded;
  String? id;
  String? title;

  static Tree fromJsons(Map<String, dynamic> json) => Tree.fromJson(json);

  Tree({
    this.children,
    this.dateAdded,
    this.id,
    this.title,
  });

  Tree.fromJson(Map<String, dynamic> json) {
    if (json["children"] != null) {
      final v = json["children"];
      final arr0 = <TreeChildren>[];
      v.forEach((v) {
        arr0.add(TreeChildren.fromJson(v));
      });
      children = arr0;
    }
    dateAdded = json["dateAdded"]?.toInt();
    id = json["id"]?.toString();
    title = json["title"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (children != null) {
      final v = children;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["children"] = arr0;
    }
    data["dateAdded"] = dateAdded;
    data["id"] = id;
    data["title"] = title;
    return data;
  }
}
